import { chromium } from 'playwright';
import { artifact, launchOptions } from './browser-runtime.mjs';
const browser=await chromium.launch(launchOptions());
const page=await browser.newPage({viewport:{width:1280,height:720}});
const errors=[];page.on('console',m=>{if(m.type()==='error'&&!m.text().includes('404 (Not Found)'))errors.push(m.text())});page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:8899',{waitUntil:'networkidle'});
await page.waitForSelector('#newTask');
await page.click('#newTask');
const dialogAfterNewTask=await page.locator('#folderDialog').evaluate(e=>e.open);
await page.click('#projectButton');
await page.waitForSelector('#folderDialog[open]');
await page.waitForSelector('.folder-item');
const folders=await page.locator('.folder-item').count();
await page.click('.folder-item');
const confirmEnabled=await page.locator('#folderConfirm').isEnabled();
await page.click('#folderConfirm');
const selectedPath=await page.locator('#projectPath').textContent();
const workspaceName=await page.locator('#projectName').textContent();
await page.click('#toggleSummaryPanel');
await page.waitForFunction(()=>!document.querySelector('#summaryPanel').hidden);
await page.click('#projectButton');
await page.waitForSelector('#folderDialog[open] .folder-item');
await page.click('#folderDialog .folder-item');
await page.click('#folderConfirm');
const nextWorkspaceName=await page.locator('#projectName').textContent();
const nextHeading=await page.locator('#emptyState h1').textContent();
const summarySync=await page.evaluate(()=>({workspace:document.querySelector('#summaryWorkspace').textContent,branch:document.querySelector('#summaryBranch').textContent,open:!document.querySelector('#summaryPanel').hidden}));
await page.click('#toggleSummaryPanel');
await page.evaluate(()=>{const root=document.querySelector('#conversation');root.innerHTML=`<div class="message-text" id="smokeMarkdown">${globalThis.__renderAssistantMarkdown('## Formula\n\nInline $E=mc^2$\n\n```js\nconst x = 1;\n```')}</div>`});
const markdown={heading:await page.locator('#smokeMarkdown h2').count(),katex:await page.locator('#smokeMarkdown .katex').count(),code:await page.locator('#smokeMarkdown pre code').count()};
await page.screenshot({path:artifact('browser-smoke.png'),fullPage:false});
console.log(JSON.stringify({dialogAfterNewTask,folders,confirmEnabled,selectedPath,workspaceName,nextWorkspaceName,nextHeading,summarySync,markdown,errors},null,2));
await browser.close();
if(dialogAfterNewTask||!folders||!confirmEnabled||!workspaceName||!nextWorkspaceName||!nextHeading?.includes(nextWorkspaceName)||summarySync.workspace!==nextWorkspaceName||!summarySync.open||!markdown.heading||!markdown.katex||!markdown.code||errors.length)process.exit(1);
