import { chromium } from 'playwright';
import { artifact, launchOptions } from './browser-runtime.mjs';
const browser=await chromium.launch(launchOptions());
const page=await browser.newPage({viewport:{width:591,height:1100},deviceScaleFactor:1,isMobile:true,hasTouch:true});
await page.goto('http://127.0.0.1:8899',{waitUntil:'networkidle'});
const box=async s=>page.locator(s).evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,display:getComputedStyle(e).display,transform:getComputedStyle(e).transform}});
const closedSidebar=await box('.sidebar');
await page.click('#toggleSidebar');
await page.waitForFunction(()=>Math.round(document.querySelector('.sidebar').getBoundingClientRect().x)===0);
const openSidebar=await box('.sidebar');
await page.click('#accountButton');
const accountMenu=await box('#accountMenu');
await page.click('#toggleSidebar');
await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().x<0);
const closedSummary=await box('#summaryPanel');
const closedSidePanel=await box('#sidePanel');
await page.click('#toggleSummaryPanel');
await page.waitForFunction(()=>!document.querySelector('#summaryPanel').hidden&&document.querySelector('#summaryPanel').getBoundingClientRect().width>0);
const openSummary=await box('#summaryPanel');
await page.click('#closeSummaryPanel');
await page.waitForFunction(()=>document.querySelector('#summaryPanel').hidden&&document.activeElement?.id==='toggleSummaryPanel');
await page.click('#toggleSidePanel');
await page.waitForFunction(()=>!document.querySelector('#sidePanel').hidden&&document.querySelector('#sidePanel').getBoundingClientRect().width>0);
const openSidePanel=await box('#sidePanel');
const result={viewport:await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth})),app:await box('.app-shell'),main:await box('.conversation-shell'),closedSidebar,openSidebar,accountButton:await box('#accountButton'),accountMenu,closedSummary,openSummary,closedSidePanel,openSidePanel,topbar:await box('.topbar'),composer:await box('.composer')};
console.log(JSON.stringify(result,null,2));
await page.screenshot({path:artifact('mobile-layout.png'),fullPage:false});

const narrow=await browser.newPage({viewport:{width:320,height:800},deviceScaleFactor:1,isMobile:true,hasTouch:true});
await narrow.goto('http://127.0.0.1:8899',{waitUntil:'networkidle'});
await narrow.click('#toggleBottomPanel');
const bottomLauncher=await narrow.evaluate(()=>{const panel=document.querySelector('#bottomPanel').getBoundingClientRect(),buttons=[...document.querySelectorAll('[data-bottom-panel-action]')].map(node=>node.getBoundingClientRect().toJSON());return {title:document.querySelector('#bottomPanelTab').textContent.trim(),visible:!document.querySelector('#bottomPanelLauncher').hidden,buttonsInside:buttons.every(rect=>rect.left>=panel.left&&rect.right<=panel.right)}});
await narrow.click('[data-bottom-panel-action="terminal"]');
const bottom=await narrow.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,panelWidth:document.querySelector('#bottomPanel').getBoundingClientRect().width,title:document.querySelector('#bottomPanelTab').textContent.trim(),utilityVisible:!document.querySelector('#bottomPanelUtility').hidden}));
await narrow.click('#closeBottomPanel');
await narrow.click('#toggleSummaryPanel');
await narrow.waitForFunction(()=>document.activeElement?.id==='closeSummaryPanel');
const summaryFocus=await narrow.evaluate(()=>({activeId:document.activeElement?.id,conversationInert:document.querySelector('.conversation-shell').inert}));
await narrow.click('#closeSummaryPanel');
await narrow.waitForFunction(()=>document.activeElement?.id==='toggleSummaryPanel');
const summaryRestore=await narrow.evaluate(()=>({activeId:document.activeElement?.id,conversationInert:document.querySelector('.conversation-shell').inert}));
await narrow.click('#toggleSidePanel');
await narrow.waitForFunction(()=>document.activeElement?.id==='closeSidePanel');
const sideFocus=await narrow.evaluate(()=>({activeId:document.activeElement?.id,conversationInert:document.querySelector('.conversation-shell').inert}));
await narrow.click('[data-side-panel-action="files"]');
await narrow.waitForFunction(()=>document.querySelector('#utilityPanelTitle').textContent==='Files');
await narrow.click('#utilityPanelAction');
await narrow.waitForSelector('#folderDialog[open]');
await narrow.keyboard.press('Escape');
await narrow.waitForFunction(()=>!document.querySelector('#folderDialog').open);
const dialogEscape=await narrow.evaluate(()=>({sideOpen:document.body.classList.contains('side-panel-open'),activeId:document.activeElement?.id}));
await narrow.click('#closeSidePanel');
await narrow.waitForFunction(()=>document.activeElement?.id==='toggleSidePanel');
const sideRestore=await narrow.evaluate(()=>({activeId:document.activeElement?.id,conversationInert:document.querySelector('.conversation-shell').inert}));
console.log(JSON.stringify({narrow:{bottomLauncher,bottom,summaryFocus,summaryRestore,sideFocus,dialogEscape,sideRestore}},null,2));
await browser.close();
if(result.viewport.scrollWidth>591||result.main.x<0||result.main.width<560||result.closedSummary.display!=='none'||result.closedSidePanel.display!=='none'||result.openSummary.width!==591||result.openSidePanel.width!==591||result.closedSidebar.x>=0||Math.abs(result.openSidebar.x)>0.5||result.openSidebar.width!==275||result.accountButton.height!==30||result.accountMenu.display==='none'||bottomLauncher.title!=='New tab'||!bottomLauncher.visible||!bottomLauncher.buttonsInside||bottom.scrollWidth>320||bottom.panelWidth!==320||bottom.title!=='Terminal'||!bottom.utilityVisible||summaryFocus.activeId!=='closeSummaryPanel'||!summaryFocus.conversationInert||summaryRestore.activeId!=='toggleSummaryPanel'||summaryRestore.conversationInert||sideFocus.activeId!=='closeSidePanel'||!sideFocus.conversationInert||!dialogEscape.sideOpen||sideRestore.activeId!=='toggleSidePanel'||sideRestore.conversationInert)process.exit(1);
