import { chromium } from 'playwright';
import { artifact, launchOptions } from './browser-runtime.mjs';
const browser=await chromium.launch(launchOptions());
const page=await browser.newPage({viewport:{width:591,height:1100},deviceScaleFactor:1,isMobile:true,hasTouch:true});
await page.goto(process.env.CODEX_WEBUI_TEST_URL||'http://127.0.0.1:8899',{waitUntil:'networkidle'});
const box=async s=>page.locator(s).evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,display:getComputedStyle(e).display,transform:getComputedStyle(e).transform}});
const closedSidebar=await box('.sidebar');
await page.click('#toggleSidebar');
await page.waitForFunction(()=>Math.round(document.querySelector('.sidebar').getBoundingClientRect().x)===0);
const openSidebar=await box('.sidebar');
const sidebarVisibility=await page.evaluate(()=>{const sidebar=document.querySelector('.sidebar'),rect=sidebar.getBoundingClientRect(),style=getComputedStyle(sidebar);return{display:style.display,visibility:style.visibility,opacity:style.opacity,zIndex:style.zIndex,topElement:document.elementFromPoint(Math.min(rect.right-10,innerWidth-10),Math.min(rect.top+20,innerHeight-10))?.closest('.sidebar')===sidebar}});
await page.screenshot({path:artifact('mobile-sidebar-open.png'),fullPage:false});
const sidebarRows=await page.locator('.sidebar .thread-item').count();
await page.locator('.sidebar .thread-item').first().click();
const sidebarClosedAfterSelection=await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().x<0,{timeout:3000}).then(()=>true).catch(()=>false);
if(!sidebarClosedAfterSelection){
  await page.click('#toggleSidebar');
  await page.waitForFunction(()=>document.querySelector('.sidebar').getBoundingClientRect().x<0);
}
const closedSummary=await box('#summaryPanel');
const closedSidePanel=await box('#sidePanel');
await page.click('#toggleSummaryPanel');
await page.waitForFunction(()=>!document.querySelector('#summaryPanel').hidden&&document.querySelector('#summaryPanel').getBoundingClientRect().width>0);
const openSummary=await box('#summaryPanel');
await page.click('#closeSummaryPanel');
await page.waitForFunction(()=>document.querySelector('#summaryPanel').hidden&&document.activeElement?.id==='toggleSummaryPanel');
await page.click('#toggleSidePanel');
await page.waitForFunction(()=>!document.querySelector('#sidePanel').hidden&&document.querySelector('#sidePanel').getBoundingClientRect().width>0);
const openSidePanel=await box('#sidePanel');
const result={viewport:await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth})),app:await box('.app-shell'),main:await box('.conversation-shell'),closedSidebar,openSidebar,sidebarVisibility,sidebarRows,sidebarClosedAfterSelection,closedSummary,openSummary,closedSidePanel,openSidePanel,topbar:await box('.topbar'),composer:await box('.composer')};
console.log(JSON.stringify(result,null,2));
await page.screenshot({path:artifact('mobile-layout.png'),fullPage:false});

const narrow=await browser.newPage({viewport:{width:320,height:800},deviceScaleFactor:1,isMobile:true,hasTouch:true});
await narrow.goto(process.env.CODEX_WEBUI_TEST_URL||'http://127.0.0.1:8899',{waitUntil:'networkidle'});
await narrow.click('#toggleBottomPanel');
const bottom=await narrow.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,panelWidth:document.querySelector('#bottomPanel').getBoundingClientRect().width,title:document.querySelector('#bottomPanelTab').textContent.trim(),utilityVisible:!document.querySelector('#bottomPanelUtility').hidden}));
await narrow.click('#bottomPanelTab');
const bottomLauncher=await narrow.evaluate(()=>{const panel=document.querySelector('#bottomPanel').getBoundingClientRect(),buttons=[...document.querySelectorAll('[data-bottom-panel-action]')].map(node=>node.getBoundingClientRect().toJSON());return {title:document.querySelector('#bottomPanelTab').textContent.trim(),visible:!document.querySelector('#bottomPanelLauncher').hidden,buttonsInside:buttons.every(rect=>rect.left>=panel.left&&rect.right<=panel.right)}});
await narrow.click('[data-bottom-panel-action="terminal"]');
await narrow.waitForFunction(()=>document.querySelector('#terminalHost')?.dataset.connected==='true');
const terminal=await narrow.evaluate(()=>({title:document.querySelector('#bottomPanelTab').textContent.trim(),utilityVisible:!document.querySelector('#bottomPanelUtility').hidden,visible:!document.querySelector('#terminalHost').hidden,connected:document.querySelector('#terminalHost').dataset.connected,xterm:Boolean(document.querySelector('#terminalHost .xterm'))}));
await narrow.click('#closeBottomPanel');
await narrow.click('#toggleSummaryPanel');
await narrow.waitForFunction(()=>document.activeElement?.id==='closeSummaryPanel');
const summaryFocus=await narrow.evaluate(()=>({activeId:document.activeElement?.id,conversationInert:document.querySelector('.conversation-shell').inert}));
await narrow.click('#closeSummaryPanel');
await narrow.waitForFunction(()=>document.activeElement?.id==='toggleSummaryPanel');
const summaryRestore=await narrow.evaluate(()=>({activeId:document.activeElement?.id,conversationInert:document.querySelector('.conversation-shell').inert}));
await narrow.click('#toggleSidePanel');
await narrow.waitForFunction(()=>document.activeElement?.id==='closeSidePanel');
const sideFocus=await narrow.evaluate(()=>({activeId:document.activeElement?.id,conversationInert:document.querySelector('.conversation-shell').inert}));
await narrow.click('[data-side-panel-action="files"]');
await narrow.waitForFunction(()=>document.querySelector('#utilityPanelTitle').textContent==='Files');
await narrow.click('#utilityPanelAction');
await narrow.waitForSelector('#folderDialog[open]');
await narrow.keyboard.press('Escape');
await narrow.waitForFunction(()=>!document.querySelector('#folderDialog').open);
const dialogEscape=await narrow.evaluate(()=>({sideOpen:document.body.classList.contains('side-panel-open'),activeId:document.activeElement?.id}));
await narrow.click('#closeSidePanel');
await narrow.waitForFunction(()=>document.activeElement?.id==='toggleSidePanel');
const sideRestore=await narrow.evaluate(()=>({activeId:document.activeElement?.id,conversationInert:document.querySelector('.conversation-shell').inert}));
console.log(JSON.stringify({narrow:{bottom,bottomLauncher,terminal,summaryFocus,summaryRestore,sideFocus,dialogEscape,sideRestore}},null,2));
await browser.close();
if(result.viewport.scrollWidth>591||result.main.x<0||result.main.width<560||result.closedSummary.display!=='none'||result.closedSidePanel.display!=='none'||result.openSummary.width!==591||result.openSidePanel.width!==591||result.closedSidebar.x>=0||Math.abs(result.openSidebar.x)>0.5||result.openSidebar.width!==275||result.sidebarVisibility.display==='none'||result.sidebarVisibility.visibility!=='visible'||result.sidebarVisibility.opacity==='0'||!result.sidebarVisibility.topElement||result.sidebarRows<1||!result.sidebarClosedAfterSelection||bottom.scrollWidth>320||bottom.panelWidth!==320||bottom.title!=='New tab'||bottom.utilityVisible||bottomLauncher.title!=='New tab'||!bottomLauncher.visible||!bottomLauncher.buttonsInside||terminal.title!=='Terminal'||terminal.utilityVisible||!terminal.visible||terminal.connected!=='true'||!terminal.xterm||summaryFocus.activeId!=='closeSummaryPanel'||!summaryFocus.conversationInert||summaryRestore.activeId!=='toggleSummaryPanel'||summaryRestore.conversationInert||sideFocus.activeId!=='closeSidePanel'||!sideFocus.conversationInert||!dialogEscape.sideOpen||sideRestore.activeId!=='toggleSidePanel'||sideRestore.conversationInert)process.exit(1);
