import { chromium } from 'playwright';
import { artifact, launchOptions } from './browser-runtime.mjs';
const browser=await chromium.launch(launchOptions());
const page=await browser.newPage({viewport:{width:591,height:1100},deviceScaleFactor:1,isMobile:true,hasTouch:true});
await page.goto('http://127.0.0.1:8899',{waitUntil:'networkidle'});
const box=async s=>page.locator(s).evaluate(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,width:r.width,height:r.height,display:getComputedStyle(e).display,transform:getComputedStyle(e).transform}});
const closedSidebar=await box('.sidebar');
await page.click('#toggleSidebar');
await page.waitForFunction(()=>Math.round(document.querySelector('.sidebar').getBoundingClientRect().x)===0);
const openSidebar=await box('.sidebar');
await page.click('#accountButton');
const accountMenu=await box('#accountMenu');
const result={viewport:await page.evaluate(()=>({innerWidth,scrollWidth:document.documentElement.scrollWidth,bodyWidth:document.body.scrollWidth})),app:await box('.app-shell'),main:await box('.conversation-shell'),closedSidebar,openSidebar,accountButton:await box('#accountButton'),accountMenu,changes:await box('.changes-panel'),topbar:await box('.topbar'),composer:await box('.composer')};
console.log(JSON.stringify(result,null,2));
await page.screenshot({path:artifact('mobile-layout.png'),fullPage:false});
await browser.close();
if(result.viewport.scrollWidth>591||result.main.x<0||result.main.width<560||result.changes.display!=='none'||result.closedSidebar.x>=0||result.openSidebar.x!==0||result.openSidebar.width!==275||result.accountButton.height!==30||result.accountMenu.display==='none')process.exit(1);
